on:
  telegram_bot:
    webhook: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          telegram_outputs: ${{ toJson(on.telegram_bot.outputs) }}
        run: |
          echo telegram: $telegram_outputs
