const fs = require("fs-extra");
const path = require("path");
const autoGeneratedMessage = `<!-- NOTE!!! This markdown file is automatically generated from <root>/README.md, please edit <root>/README.md if you need to change it-->`;
async function main() {
  const from = path.resolve(__dirname, "../README.md");
  const toPackage = path.resolve(
    __dirname,
    "../packages/actionsflow/README.md"
  );
  const content = await fs.readFileSync(from, "utf-8");
  const finalContent = autoGeneratedMessage + "\n\n" + content;
  await fs.writeFile(toPackage, finalContent);
  console.log("sync readme file successfully");
  // add <!-- auto generate  -->
}
main().catch((e) => {
  console.error(e);
});
